### ISSUE TITLE
SG300 throws error on `show running-config brief`

### ISSUE THREAD

**Issue by miken32** [chrpinedo/rancid-cisco-sb#10]
```
Switch3#show version
SW version    1.1.2.0 ( date  12-Nov-2011 time  23:34:26 )
Boot version    1.0.0.4 ( date  08-Apr-2010 time  16:37:57 )
HW version    V01
Switch3#show running-config brief
% Wrong number of parameters or invalid range, size or characters entered
```

**Comment by chrpinedo** [comment]
According to this cisco manual http://www.cisco.com/c/dam/en/us/td/docs/switches/lan/csbms/sf30x_sg30x/administration_guide/CLI_Nikola300_1_3_7.pdf  SG and SF devices should support this command, although perhaps this has changed with new versions. In any case, "show running-config" is going to work with devices with "show running-config brief" command but not viceversa. So, I change the command to "show running-config".

**Comment by chrpinedo** [comment]
I have decided also to replace the backup of "running-config" with the backup of "startup-config". I think it is more important to save saved configuration and not temporal configuration.
