### ISSUE TITLE
rancid backup updated every time because of uptime

### ISSUE THREAD

**Issue by chrpinedo** [chrpinedo/rancid-cisco-sb#14]
@jbilder reported the next issue:

Thanks for creating this script. It's been extremely useful in environments where i support these devices. One issue I have seems to be with the Uptime changing on the device, so it causes rancid to send diffs every hour:

!Unit Up time
!---- ---------------

    ! 1 253,00:32:08
    ! 1 253,01:32:09

Please let me know how to go about excluding these changes from updates.

Thanks!

**Comment by chrpinedo** [comment]
@jbilder first of all I would suggest to use the updated csblogin and csbrancid files to ensure that this is not already solved (firstly backup your old ones and then override the old ones with the updated files).

If the problem appears with the new csblogin/csbrancid scripts, then let's verify what it is happening. These scripts uses three CLI commands to do the backup: show version, show version and show startup-config. One of these commands it causing the problem.

Nowadays, I don't have access this type of cisco switches. Could you post here the output of these commands (removing all sensitive data)? or at least provide the output of the previous command that produces the uptime output?

Thanks for your feedback!
Thanks!

**Comment by fasa01** [comment]
Hi  chrpinedo,

i facing the same issue ... thanks for the solution for sg500x family it runs like a charm!

how you would get the output, from any rancid debugging function or direct from the console?
if you prefer this from rancid then please tell me the command line, sorry i'm new on rancid.

regards
  Falk

**Comment by chrpinedo** [comment]
@fasa01 our scripts use three CLI commands to get the data: show version, show version and show startup-config. So, one of these commands it causing the problem. It would be nice if you could test these commands and provide the output of the problematic command (removing all sensitive data firstly). Thanks!!

**Comment by fasa01** [comment]
Hi chrpinedo,

Am Freitag, 30. Oktober 2015, 04:07:13 schrieb chrpinedo:
>@fasa01 our scripts use three CLI commands to get the data: show
>version, show version and show startup-config.

are you shure that the first and the second command is 'show version' ? 
;-)

show version is definitiv not the problem ...

the problematic output comes also not from 'show startup-config'

it comes from the /unknown/ ;-) 'show system'

csw-a#show system

Unit          Type          
---- ---------------------- 
 1        SG500XG-8F8T      
 2        SG500XG-8F8T      
 3        SG500XG-8F8T      
 4         SG500X-24P       
 5         SG500X-48        
 6         SG500X-48        
 7         SG500X-48        

Unit   FAN       
       Status    
----   --------- 
 1        OK       
 2        OK       
 3        OK       
 4        OK       
 5        OK       
 6        OK       
 7        OK       

Unit   Temperature (Celsius)   Temperature Sensor Status 
---- ------------------------- ------------------------- 
 1              48                        OK             
 2              61                        OK             
 3              57                        OK             
 4              32                        OK             
 5                                        N/A            
 6                                        N/A            
 7                                        N/A            


Unit     Up time     
---- --------------- 
 1     32,12:38:03   
 2     32,12:36:47   
 3     32,12:37:55   
 4     32,12:37:10   
 5     32,12:36:10   
 6     32,12:34:58   
 7     32,12:36:16   

csw-a#

the problematic part is the last part, i think this should be possible 
to remove all begins with 'Up time' or 'Unit     Up time', but i don't 
know how.

with best regards
Falk

**Comment by chrpinedo** [comment]
Could you check the new proposed csbrancid file? https://github.com/chrpinedo/rancid-cisco-sb/blob/fixes-14/src/csbrancid

**Comment by fasa01** [comment]
Hi Chrpinedo,

Am 02.11.2015 um 12:54 schrieb chrpinedo:
>
> Could you check the new proposed csbrancid file? 
> https://github.com/chrpinedo/rancid-cisco-sb/blob/fixes-14/src/csbrancid
>
thank's a lot for this try, but it looks as is it not the whole solution.

look on the rancid mail before the new version:

Index: configs/csw-a...
===================================================================
retrieving revision 1.113
diff -u -4 -r1.113 csw-a...
@@ -18,15 +18,15 @@
   ! 6                                        N/A
   ! 7                                        N/A
   !Unit     Up time
   !---- ---------------
- ! 1     35,10:29:05
- ! 2     35,10:27:48
- ! 3     35,10:28:58
- ! 4     35,10:28:15
- ! 5     35,10:27:16
- ! 6     35,10:26:04
- ! 7     35,10:27:23
+ ! 1     35,11:29:05
+ ! 2     35,11:27:48
+ ! 3     35,11:28:58
+ ! 4     35,11:28:15
+ ! 5     35,11:27:16
+ ! 6     35,11:26:04
+ ! 7     35,11:27:23
   !
   !       Unit             SW version         Boot version         HW version
   !------------------- ------------------- ------------------- -------------------
   !         1                1.4.1.3            1.4.0.02               V03


and the first after the modification

Index: configs/csw-a...
===================================================================
retrieving revision 1.114
diff -u -4 -r1.114 csw-a...
@@ -16,17 +16,16 @@
   !---- ------------------------- -------------------------
   ! 5                                        N/A
   ! 6                                        N/A
   ! 7                                        N/A
- !Unit     Up time
   !---- ---------------
- ! 1     35,11:29:05
- ! 2     35,11:27:48
- ! 3     35,11:28:58
- ! 4     35,11:28:15
- ! 5     35,11:27:16
- ! 6     35,11:26:04
- ! 7     35,11:27:23
+ ! 1     35,12:19:13
+ ! 2     35,12:17:56
+ ! 3     35,12:19:06
+ ! 4     35,12:18:23
+ ! 5     35,12:17:24
+ ! 6     35,12:16:12
+ ! 7     35,12:17:31
   !
   !       Unit             SW version         Boot version         HW version
   !------------------- ------------------- ------------------- -------------------
   !         1                1.4.1.3            1.4.0.02               V03


and the second after the modification

Index: configs/csw-a...
===================================================================
retrieving revision 1.115
diff -u -4 -r1.115 csw-a...
@@ -17,15 +17,15 @@
   ! 5                                        N/A
   ! 6                                        N/A
   ! 7                                        N/A
   !---- ---------------
- ! 1     35,12:19:13
- ! 2     35,12:17:56
- ! 3     35,12:19:06
- ! 4     35,12:18:23
- ! 5     35,12:17:24
- ! 6     35,12:16:12
- ! 7     35,12:17:31
+ ! 1     35,12:29:05
+ ! 2     35,12:27:48
+ ! 3     35,12:28:58
+ ! 4     35,12:28:15
+ ! 5     35,12:27:16
+ ! 6     35,12:26:04
+ ! 7     35,12:27:23
   !
   !       Unit             SW version         Boot version         HW version
   !------------------- ------------------- ------------------- -------------------
   !         1                1.4.1.3            1.4.0.02               V03


you can see the suppression goes only thru the end of the 'Up Time' line 
... we need a suppression thru the end of the ShowSystem command block.

regards
   Falk

**Comment by chrpinedo** [comment]
Thanks for your quick reply. Please could you attach the output of the "show system" command in a txt file? Because it is important to see the spaces, tabulars, ... This detail is lost pasting the output of "show system" in these posts. 

It would be nice if you could attach txt files in one comment for the "show system" output and for the diff of your version control.

Thanks!

**Comment by fasa01** [comment]
Hi Chrpinedo,

Am 02.11.2015 um 17:51 schrieb chrpinedo:
>
> Thanks for your quick reply. Please could you attach the output of the 
> "show system" command in a txt file? Because it is important to see 
> the spaces, tabulars, ... This detail is lost pasting the output of 
> "show system" in these posts.
>
> It would be nice if you could attach txt files in one comment for the 
> "show system" output and for the diff of your version control.
>
i can't guarantee that this characters are not modified on copying over 
ctrl-c/ctrl-v

regards
  Falk

Index: configs/csw-a...
===================================================================
retrieving revision 1.116
diff -u -4 -r1.116 csw-a...
@@ -17,15 +17,15 @@
  ! 5                                        N/A            
  ! 6                                        N/A            
  ! 7                                        N/A            
  !---- --------------- 
- ! 1     35,12:29:05   
- ! 2     35,12:27:48   
- ! 3     35,12:28:58   
- ! 4     35,12:28:15   
- ! 5     35,12:27:16   
- ! 6     35,12:26:04   
- ! 7     35,12:27:23   
+ ! 1     35,13:29:05   
+ ! 2     35,13:27:49   
+ ! 3     35,13:28:58   
+ ! 4     35,13:28:15   
+ ! 5     35,13:27:17   
+ ! 6     35,13:26:05   
+ ! 7     35,13:27:23   
  !
  !       Unit             SW version         Boot version         HW version      
  !------------------- ------------------- ------------------- ------------------- 
  !         1                1.4.1.3            1.4.0.02               V03         

csw-a#show system

Unit          Type          
---- ---------------------- 
 1        SG500XG-8F8T      
 2        SG500XG-8F8T      
 3        SG500XG-8F8T      
 4         SG500X-24P       
 5         SG500X-48        
 6         SG500X-48        
 7         SG500X-48        

Unit   FAN       
       Status    
----   --------- 
 1        OK       
 2        OK       
 3        OK       
 4        OK       
 5        OK       
 6        OK       
 7        OK       

Unit   Temperature (Celsius)   Temperature Sensor Status 
---- ------------------------- ------------------------- 
 1              48                        OK             
 2              59                        OK             
 3              57                        OK             
 4              32                        OK             
 5                                        N/A            
 6                                        N/A            
 7                                        N/A            


Unit     Up time     
---- --------------- 
 1     35,13:43:39   
 2     35,13:42:22   
 3     35,13:43:31   
 4     35,13:42:48   
 5     35,13:41:50   
 6     35,13:40:38   
 7     35,13:41:57   

csw-a#

**Comment by chrpinedo** [comment]
I think now is done. Could you test this file:  https://github.com/chrpinedo/rancid-cisco-sb/blob/fixes-14/src/csbrancid? If it is ok I would update the master branch with this patch.

**Comment by fasa01** [comment]
Hi Chrpinedo,

Am 04.11.2015 um 12:11 schrieb chrpinedo:
>
> I think now is done. Could you test this file: 
> https://github.com/chrpinedo/rancid-cisco-sb/blob/fixes-14/src/csbrancid? 
> If it is ok I would update the master branch with this patch.
>
>
now it looks good!

many thanks!

with best regards
   Falk

**Comment by chrpinedo** [comment]
Thanks for your feedback!

**Comment by xaok** [comment]
Hi,

there is still an issue with SG500X-48P with SW version 1.4.0.88:

diff -r1.7 192.168.10.25
5c5
< !System Up Time (days,hour:min:sec):       189,02:37:26
---
> !System Up Time (days,hour:min:sec):       189,02:45:19

**Comment by chrpinedo** [comment]
@xaok Could you print me the output of the "show system" CLI command for your SG500X-48P with SW version 1.4.0.88 as @fasa01 did it before? I could try to solve it.

**Comment by xaok** [comment]
sure, here it is:

SW20-KW-OG1#show system
System Description:                       SG500X-48P 48-Port Gigabit with 4-Port 10-Gigabit PoE Stackable Managed Switch
System Up Time (days,hour:min:sec):       220,14:04:06
System Contact:                           xxx
System Name:                              SW20-KW-OG1
System Location:                          xxx
System MAC Address:                       d4:d7:48:xxxxxxxxx
System Object ID:                         1.3.6.1.4.1.9.6.1.85.48.2

Fans Status:                              OK


          Unit            Temperature (Celsius)            Status          
------------------------ ------------------------ ------------------------ 
           1                        37                       OK

**Comment by chrpinedo** [comment]
Could you try this new csbrancid file https://github.com/chrpinedo/rancid-cisco-sb/blob/bug-avoid-uptime/src/csbrancid and provide the output obtained? Thanks,

**Comment by xaok** [comment]
seems to be working, no more new revisions are created just because of uptime change.

thx a lot for the nice work on cisco-sb and rancid!

**Comment by chrpinedo** [comment]
@fasa01, it would be nice if you could try this patch also (https://github.com/chrpinedo/rancid-cisco-sb/blob/bug-avoid-uptime/src/csbrancid) to verify that it continues working right with your devices.

**Comment by fasa01** [comment]
Hi Christian,

Am 16.11.2015 um 09:56 schrieb Christian Pinedo:
>
> @fasa01 <https://github.com/fasa01>, it would be nice if you could try 
> this patch also 
> (https://github.com/chrpinedo/rancid-cisco-sb/blob/bug-avoid-uptime/src/csbrancid) 
> to verify that it continues working right with your devices.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/chrpinedo/rancid-cisco-sb/issues/14#issuecomment-156958871>.
>

looks good so far.

-- 
Gruss
   Falk

**Comment by chrpinedo** [comment]
Thanks @fasa01 for your support! I apply this change in the main branch :-)

**Comment by fasa01** [comment]
sorry, i see the patch is not working for me, the previous version was 
perfect, the actual version has new problem that i yesterday not seen ...

here the log:


starting: Di 17. Nov 10:40:13 CET 2015



Trying to get all of the configs.
csw-a.hb-fein.de: found unexpected command - "show system"
csw-a.hb-fein.de: missed cmd(s): show version,show startup-config
csw-a.hb-fein.de: End of run not found
!
=====================================
Getting missed routers: round 1.
csw-a.hb-fein.de: found unexpected command - "show system"
csw-a.hb-fein.de: missed cmd(s): show version,show startup-config
csw-a.hb-fein.de: End of run not found
!
=====================================
Getting missed routers: round 2.
csw-a.hb-fein.de: found unexpected command - "show system"
csw-a.hb-fein.de: missed cmd(s): show version,show startup-config
csw-a.hb-fein.de: End of run not found
!
=====================================
Getting missed routers: round 3.
csw-a.hb-fein.de: found unexpected command - "show system"
csw-a.hb-fein.de: missed cmd(s): show version,show startup-config
csw-a.hb-fein.de: End of run not found
!
=====================================
Getting missed routers: round 4.
csw-a.hb-fein.de: found unexpected command - "show system"
csw-a.hb-fein.de: missed cmd(s): show version,show startup-config
csw-a.hb-fein.de: End of run not found
!

cvs diff: Diffing .
cvs diff: Diffing configs
cvs commit: Examining .
cvs commit: Examining configs

ending: Di 17. Nov 10:43:29 CET 2015
~


Am Montag, 16. November 2015, 09:56:22 schrieb Christian Pinedo:
> @fasa01, it would be nice if you could try this patch also
> (https://github.com/chrpinedo/rancid-cisco-sb/blob/bug-avoid-uptime/src/cs
> brancid) to verify that it continues working right with your devices.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/chrpinedo/rancid-cisco-sb/issues/14#issuecomment-1569588
> 71

-- 
Gruss
      Falk
