### ISSUE TITLE
Add support for alternate SSH ports

### ISSUE THREAD

**Issue by engageant** [chrpinedo/rancid-cisco-sb#4]
Is it possible to add support for alternate SSH ports as defined in .cloginrc?  It looks like this may be there for telnet, but I can't seem to modify it for SSH.  For example...if:

add method sg300.foo.com {ssh:2222}

is in .cloginrc, csblogin should add -p 2222 to the ssh arguments.

Thanks!

**Comment by chrpinedo** [comment]
I have prepared one patch but I can't test it with real equipments. Could you test it and provide me with some feedback?

* Configure the switch with the desired ssh port

```
add method test.example.com        {ssh:2222}
```

* Use the csblogin and csbrancid files of the 79ff9f93153f5bb7a6aecf5d7f9a6a3e23f7982d commit.

**Comment by engageant** [comment]
Apologies but I no longer have access to any Cisco SMB devices to test
with.

**Comment by chrpinedo** [comment]
Apologies for moving this issue so late :) Since I don't have also Cisco SMB devices, I will try to verify that with this patch rancid tries to establish a remote connection with port TCP/2222 and if it is right I would include the patch. Thanks @engageant !
